const dummyData = [
  {
    id: 6,
    type: 'audio',
    title: 'Ep. 6: Bigger, Longer, Uncut',
    teaser: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, accusamus.',
    content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nam consequuntur voluptatem maiores unde ipsum enim, odit eius ea magni blanditiis ut, ex quae iste inventore cum, eveniet tenetur recusandae laborum!',
    media: '',
    date: new Date(2017, 1, 7),
  },
  {
    id: 5,
    type: 'audio',
    title: 'Ep. 5: Cinco The Episode',
    teaser: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, accusamus.',
    content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nam consequuntur voluptatem maiores unde ipsum enim, odit eius ea magni blanditiis ut, ex quae iste inventore cum, eveniet tenetur recusandae laborum!',
    media: '',
    date: new Date(2017, 1, 2),
  },
  {
    id: 4,
    type: 'article',
    title: 'The Writing Contest',
    teaser: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, accusamus.',
    content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nam consequuntur voluptatem maiores unde ipsum enim, odit eius ea magni blanditiis ut, ex quae iste inventore cum, eveniet tenetur recusandae laborum!',
    date: new Date(2016, 12, 29),
  },
  {
    id: 3,
    type: 'video',
    title: 'How to Get Away with Jaywalking',
    teaser: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, accusamus.',
    content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nam consequuntur voluptatem maiores unde ipsum enim, odit eius ea magni blanditiis ut, ex quae iste inventore cum, eveniet tenetur recusandae laborum!',
    media: '',
    date: new Date(2016, 12, 23),
  },
  {
    id: 2,
    type: 'audio',
    title: 'Ep. 4: Fourth Times a Charm',
    teaser: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, accusamus.',
    content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nam consequuntur voluptatem maiores unde ipsum enim, odit eius ea magni blanditiis ut, ex quae iste inventore cum, eveniet tenetur recusandae laborum!',
    media: '',
    date: new Date(2016, 12, 11),
  },
  {
    id: 1,
    type: 'article',
    title: 'What happened there?!',
    teaser: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, accusamus.',
    content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nam consequuntur voluptatem maiores unde ipsum enim, odit eius ea magni blanditiis ut, ex quae iste inventore cum, eveniet tenetur recusandae laborum!',
    date: new Date(2016, 12, 4),
  },
];

export default dummyData;