export default [
  {
    id: 2,
    type: 'audio',
    title: 'Ep. 4: Fourth Times a Charm',
    teaser: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, accusamus.',
    content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nam consequuntur voluptatem maiores unde ipsum enim, odit eius ea magni blanditiis ut, ex quae iste inventore cum, eveniet tenetur recusandae laborum!',
    media: '//mmmyesquite.com/wp-content/uploads/sites/3/2016/05/ep5_audio.m4a',
    date: new Date(2016, 12, 11),
    length: 3334,
  },
  {
    id: 6,
    type: 'audio',
    title: 'Ep. 6: Bigger, Longer, Titties',
    teaser: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, accusamus.',
    content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nam consequuntur voluptatem maiores unde ipsum enim, odit eius ea magni blanditiis ut, ex quae iste inventore cum, eveniet tenetur recusandae laborum!',
    media: '//mmmyesquite.com/wp-content/uploads/sites/3/2016/05/ep6_audio.m4a',
    date: new Date(2017, 1, 7),
    length: 3334,
  },
  {
    id: 5,
    type: 'audio',
    title: 'Ep. 5: Cinco The Episode',
    teaser: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, accusamus.',
    content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nam consequuntur voluptatem maiores unde ipsum enim, odit eius ea magni blanditiis ut, ex quae iste inventore cum, eveniet tenetur recusandae laborum!',
    media: '//mmmyesquite.com/wp-content/uploads/sites/3/2016/05/ep4_audio.m4a',
    date: new Date(2017, 1, 2),
    length: 709,
  },
];